name: Build

on:
  workflow_dispatch:
    inputs:
      arch:
        description: "Architecture"
        required: true
        default: "x86_64"
        type: choice
        options: 
        - "arm"
        - "arm64"
        - "x86"
        - "x86_64"
      androidv:
        description: "Android Version"
        required: true
        default: "12.1"
        type: choice
        options:
        - "9"
        - "10"
        - "11"
        - "12.1"
        - "13"
        
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
      - name: Cache repository
        id: cache-repository
        uses: actions/cache@v3
        with:
          path: |
            vendor_gapps/*
            !vendor_gapps/out
          key: MindTheGapps-${{ hashFiles('**/packed-refs') }}
          restore-keys: MindTheGapps-

      - name: Map Android Version to tree
        run: |
          declare -A ANDROID_VER_MAP=([9]="pi" [10]="qoppa" [11]="rho" ["12.1"]="sigma" [13]="tau")
          ANDROID_VER=${ANDROID_VER_MAP[${{ github.event.inputs.androidv }}]}
          echo "ANDROIDV=$ANDROID_VER" >> $GITHUB_ENV

      - name: Clone repository
        if: steps.cache-repository.outputs.cache-hit != 'true'
        run: |
          rm -rf vendor_gapps
          git clone -b ${{ env.ANDROIDV }} --filter=tree:0 https://gitlab.com/MindTheGapps/vendor_gapps.git

      - name: Update repository
        if: steps.cache-repository.outputs.cache-hit == 'true'
        run: |
          cd ./vendor_gapps
          git clean -fxd
          git switch ${{ env.ANDROIDV }}
          git pull

      - name: Build
        run: |
          ANDROID_VER=${{ env.ANDROIDV }}
          cd ./vendor_gapps
          if [ "$ANDROID_VER" = "sigma" ] || [ "$ANDROID_VER" = "tau" ]; then
            sudo apt-get install -y aapt zipalign
            mkdir -p common/proprietary/product/overlay
            keytool -genkey -v -keystore debug.keystore -alias androiddebugkey -keyalg RSA -validity 10000 -dname "CN=Android Debug,O=Android,C=US" -storepass android
            aapt package -M overlay/GmsSettingsProviderOverlay/AndroidManifest.xml -S overlay/GmsOverlay/res/ -I /usr/local/lib/android/sdk/platforms/android-32/android.jar -F GmsSettingsProviderOverlay.apk.u
            jarsigner -keystore ./debug.keystore GmsSettingsProviderOverlay.apk.u androiddebugkey -storepass android
            zipalign 4 GmsSettingsProviderOverlay.apk.u GmsSettingsProviderOverlay.apk
            aapt package -M overlay/GmsOverlay/AndroidManifest.xml -S overlay/GmsSettingsProviderOverlay/res/ -I /usr/local/lib/android/sdk/platforms/android-32/android.jar -F GmsOverlay.apk.u
            jarsigner -keystore ./debug.keystore GmsOverlay.apk.u androiddebugkey -storepass android
            zipalign 4 GmsOverlay.apk.u GmsOverlay.apk
            mv *.apk common/proprietary/product/overlay
          fi
          make gapps_"${{ github.event.inputs.arch }}"
          DATA=$(date -u +%Y%m%d_%H%M%S)
          echo "DATA=$DATA" >> $GITHUB_ENV

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Built_MindTheGapps-${{ github.event.inputs.androidv }}-${{ github.event.inputs.arch }}-${{ env.DATA }}
          path: ./vendor_gapps/out/*
